[sqldetector]
stop_after_first_finding = false
max_connections = 12
max_keepalive_connections = 6
timeout_connect = 6.0
timeout_read    = 12.0
hedge_enabled = true
hedge_delay_ms = 150
max_pages = 300
max_forms_per_page = 2
max_tests_per_form = 1
max_body_kb = 512
skip_binary_ext = ["jpg","jpeg","png","gif","webp","svg","ico","pdf","zip","gz","rar","7z","mp4","mp3","woff","woff2"]
use_llm = "auto"
