[sqldetector]
stop_after_first_finding = false
max_connections = 15
max_keepalive_connections = 6
timeout_connect = 5.0
timeout_read    = 12.0
max_pages = 80
max_forms_per_page = 10
max_tests_per_form = 5
max_body_kb = 512
skip_binary_ext = ["jpg","jpeg","png","gif","webp","svg","ico","pdf","zip","gz","rar","7z","mp4","mp3","woff","woff2"]
use_llm = "auto"
