[sqldetector]
stop_after_first_finding = false
max_connections = 4
max_keepalive_connections = 2
timeout_connect = 5.0
timeout_read    = 10.0
timeout_write   = 10.0
timeout_pool    = 5.0
hedge_enabled = false
retry_budget = { total = 2, per_host = 1 }
max_pages = 80
max_forms_per_page = 2
max_tests_per_form = 1
max_body_kb = 512
skip_binary_ext = ["jpg","jpeg","png","gif","webp","svg","ico","pdf","zip","gz","rar","7z","mp4","mp3","woff","woff2"]
use_llm = "auto"
