name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: \
            ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - run: pip install ruff black
      - run: ruff .
      - run: black --check .

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: \
            ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - run: pip install -e .[test]
      - run: pytest -q
